name: EPG Update
on:
  push:
  schedule:
    - cron: '15 16,18,20,22,0,2,4,6,8,10,12,14 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update EPG Files
      run: |
        rm -f e.xml && wget https://epg.112114.xyz/pp.xml -O e.xml
        rm -f e.xml.gz && wget http://epg.51zmt.top:8000/e.xml.gz -O e.xml.gz
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add e.xml e.xml.gz
        git commit -m "EPG Automatic Update."
    - name: Push changes
      run: git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
