name: m3u8

on:
  schedule:
    - cron: '15 16,18,20,22,0,2,4,6,8,10,12,14 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python m3u8.py
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
